### ISSUE TITLE
Checking if connection is successful

### ISSUE THREAD

**Issue by christoffersch** [Malkverbena/MySQL_Module#1]
Loving the module so far. _Thanks_ for developing it!

I'd like to be able to check if the connection is successful or not (e.g. something like `mysql.check_connection()` that could return a boolean for whether or not a connection has been successfully established.

**Comment by Malkverbena** [comment]
Sorry for take so long to answer. 
I like your idea. I was thinking in someting like that some time ago but I just gave up to work on this due the lack of time.
Anyway, you can see on error log if the connections has ben successful.
Any idea and help are very welcome and if you could write the code I can merge it.

**Comment by Malkverbena** [comment]
One more thing. The module does not stay connected all the time. After the query is done, the connections are closed.

**Comment by Malkverbena** [comment]
I've changed the way as the module works. There is a new function that returns the status of the connection.
