### ISSUE TITLE
Module not working on Linux server

### ISSUE THREAD

**Issue by Samulikoo** [Malkverbena/MySQL_Module#11]
Hello! The module is not working on my linux server. I compiled the Godot Engine from source and it worked on windows and connected to MySQL database but then I created a linux export template and whenever I run the file it doesn't work and doesn't say anything in the console after it has tried to connect to the database.

Godot version: 3.2.3
Linux version: Ubuntu Linux 20.04.2
Compile commands: scons platform=server target=release tools=no

I think there is some problems in the mysqlcppconn library, I installed the library with the command sudo apt-get install libmysqlcppconn-dev.

**Comment by Malkverbena** [comment]
HI! 
Sorry for take so long to answer. I have no clue about what can be happening. 
Usually this module has problems on Windows. 
Could you send a small project reproducing the issue?

**Comment by Samulikoo** [comment]
I had a simple test project:

`
func _ready():
    mysql = MySQL.new()
    mysql.set_credentials( "127.0.0.1", "root", "-") 
    mysql.connection_start()
    print("ok") # Console not printing that
`

**Comment by Malkverbena** [comment]
Are you using the branch 1.x, right??

**Comment by Samulikoo** [comment]
Okay good!
