### ISSUE TITLE
Error building godot on windows

### ISSUE THREAD

**Issue by fenix-hub** [Malkverbena/MySQL_Module#3]
Hi , I'm trying to add this module on Windows.
While building godot i get the error : `'mysql_error.h' : no such file or directory`
What should I do? Thank you!

**Comment by Malkverbena** [comment]
Hi, sorry for take so long to answer. Lack of time...
Compile anything due this connector to Windows can be very annoying.
I gonna leave a step-by-step on README.md.
If after that you still get any issues, let me know.

**Comment by nicolausaugusto** [comment]
Thank you very much!

**Comment by nicolausaugusto** [comment]
In the README.md file with "libmysqlcppconn.windows.tools.64.lib" do you mean "mysqlcppconn.windows.tools.64.lib" ?

**Comment by Malkverbena** [comment]
If you are still having this error:  "'mysql_error.h': no such file or directory", you have not edited the SCsub file correctly.
You must use the path to the file inside SCsub.
What is the path to this file in your machine?
