### ISSUE TITLE
Error with android

### ISSUE THREAD

**Issue by manfredhq** [Malkverbena/MySQL_Module#4]
Hello,

I get some errors when i try to load a scene using this module on android.
On my pc everything work fine but when i want to export and use it on my android device i get these errors
![Capture](https://user-images.githubusercontent.com/38951963/70136364-25955e80-168c-11ea-86fc-7522acf431e0.PNG)

When i remove all the mysql module related code the scene changement work fine.

ps: I gave the internet permission to the app.

**Comment by Malkverbena** [comment]
This module is actually a wrap of mysql connector. It's designed for desktop OS, like Linux and Windows. If there is any way to make it work on any mobile platform, I don't know. Anyway this would require a lot of work with SDK and source code.
