### ISSUE TITLE
Error trying to compile 3.2.3

### ISSUE THREAD

**Issue by KaiserCristoph** [Malkverbena/MySQL_Module#6]
Hi! I'm new adding modules to godot, and im seeing this error while trying to compile from the powershell:
![image](https://user-images.githubusercontent.com/69873677/103398496-c8ccd780-4b1b-11eb-95b7-04ae6346519b.png)

Its like trying to find a non-existing file, can anyone help me with this error?

**Comment by KaiserCristoph** [comment]
I've managed to fix it,
If you are using windows get rid of those lines:
![image](https://user-images.githubusercontent.com/69873677/103449519-f6cf2a80-4c87-11eb-90cb-2fbc5244f581.png)

they kind mess up with the "windows=platform" option

**Comment by Malkverbena** [comment]
Sorry for that dude.
I'll fix this.

**Comment by Malkverbena** [comment]
I think everything is ok now.
Please let me know if it's running fine for you.

**Comment by romssprogrammer** [comment]
Hello Malkverbena  first of all  thank you for your work.
it's seems  i have  the same issue but when i try to fix it it's not a success

![cmdCap](https://user-images.githubusercontent.com/60788468/113292326-a4d48a00-92f4-11eb-8203-66ce28693384.JPG)

scsub capture

![SCsub](https://user-images.githubusercontent.com/60788468/113294263-0f86c500-92f7-11eb-9827-b97d130a0f7b.JPG)
do you know if there are other solution for this?

thank you for your help
