### ISSUE TITLE
Error Exporting proyect

### ISSUE THREAD

**Issue by babyvancho** [Malkverbena/MySQL_Module#8]
Hello. I am having trouble running the project outside of Godot. When I run it I get the error: "The identifier" MySQL "isn't declared in the current scope". I have copied the files from MySQL but it doesn't work for me. If I run it from Godot it does not give me problems. Could you help me? Thanks!

**Comment by Malkverbena** [comment]
Do you use Windows?
if yes, did you copy the dll files from mysql C++ connector to the executable file (/bin)?

**Comment by babyvancho** [comment]
Hi, yes, I use windows and the 1.x branch. Godot's version is stable 3.3.2 and the c ++ connector 8.0.25

**Comment by Malkverbena** [comment]
What is the error you get?

**Comment by babyvancho** [comment]
Hello, this is the error:
![imagen](https://user-images.githubusercontent.com/86560086/124000260-ab49cf00-d9d3-11eb-8868-6eaba5072def.png)

**Comment by Malkverbena** [comment]
Did you compile the module with the engine?

**Comment by babyvancho** [comment]
> 
> 
> Did you compile the module with the engine?

Hello, there is no solution to the error that you indicate to me?

**Comment by Malkverbena** [comment]
I can't figure out what is going on. I can't reproduce the issue. Could you call me on Discord? We can debug it.
